/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package editor;

/**
 *
 * @author student
 */
public class okno1 extends javax.swing.JDialog {
    String actionButton = "storno";
    /**
     * Creates new form okno1
     */
    public okno1(java.awt.Frame parent, boolean modal, String nahrazText,String newTxt){
        super(parent, modal);
        initComponents();
        nahraditText.setText(nahrazText);
        novyText.setText(newTxt);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nahraditButton = new javax.swing.JButton();
        stornoButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nahraditText = new javax.swing.JTextField();
        novyText = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nahraditButton.setText("nahradit");
        nahraditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nahraditButtonActionPerformed(evt);
            }
        });

        stornoButton.setText("storno");
        stornoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stornoButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("nehrazovci text");

        jLabel2.setText("nový text");

        nahraditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nahraditTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(95, 95, 95)
                        .addComponent(nahraditButton)
                        .addGap(38, 38, 38)
                        .addComponent(stornoButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nahraditText, javax.swing.GroupLayout.DEFAULT_SIZE, 158, Short.MAX_VALUE)
                            .addComponent(novyText))))
                .addGap(96, 96, 96))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(nahraditText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(novyText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nahraditButton)
                    .addComponent(stornoButton))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nahraditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nahraditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nahraditTextActionPerformed

    private void nahraditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nahraditButtonActionPerformed
        actionButton = "Nahradit";
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_nahraditButtonActionPerformed

    public String showDialog(){
        this.setVisible(true);
        return actionButton;
    }
    
    
    private void stornoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stornoButtonActionPerformed
        actionButton = "Storno";
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_stornoButtonActionPerformed
    public String getNahraditText(){
        return nahraditText.getText();
    }
    
    public String getNovyText(){
        return novyText.getText();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton nahraditButton;
    private javax.swing.JTextField nahraditText;
    private javax.swing.JTextField novyText;
    private javax.swing.JButton stornoButton;
    // End of variables declaration//GEN-END:variables
}
